# Generated by Django 5.2.11 on 2026-03-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("credit_card", "Credit Card"),
                    ("debit_card", "Debit Card"),
                    ("bank_transfer", "Bank Transfer"),
                    ("other", "Other"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
