# Generated by Django 5.2.11 on 2026-03-06 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_familymember_alter_budget_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_recurring_source",
            field=models.BooleanField(
                default=False,
                help_text="True if this is the original recurring expense",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="recurrence",
            field=models.CharField(
                choices=[
                    ("one_time", "One Time"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("half_yearly", "Half Yearly"),
                    ("annual", "Annual"),
                ],
                default="one_time",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="recurring_parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Points to the original expense that spawned this recurrence",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_children",
                to="expenses.expense",
            ),
        ),
    ]
