# Generated by Django 5.2.11 on 2026-03-08 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_expense_is_recurring_source_expense_recurrence_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="familymember",
            name="is_family_admin",
            field=models.BooleanField(
                default=False, help_text="Admin can see all family data"
            ),
        ),
        migrations.AddField(
            model_name="familymember",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="family_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
